### ISSUE TITLE
alipay.verify_notify(**request.args) failed in Flask 0.10

### ISSUE THREAD

**Issue by JoshYuJump** [lxneng/alipay#11]
alipay.verify_notify(**request.args) failed in flask 0.10,
Are there any examples in Flask?

**Comment by lxneng** [comment]
应该和 `Flask` 没什么关系， 有什么错误提示？
确保 `**request.args` 里面的 `values` 是否为 `UTF-8`。

**Comment by JoshYuJump** [comment]
request.args 里面都是 类似
u'\u5b98\u7f51\u8d2d\u4e70\u83e0\u83dc\u5dfb\u4e3b\u9898\u63a8\u5e7f\u7cfb\u7edf'
这样的
