### ISSUE TITLE
您的readme文档，关于wap支付这部分代码写的不对的吧？

### ISSUE THREAD

**Issue by benliu723** [lxneng/alipay#23]
alipay_wap = Alipay(pid='your_alipay_pid', key='your_alipay_key', seller_id='your_seller_id')

是否应该为

alipay_wap = WapAlipay(pid='your_alipay_pid', key='your_alipay_key', seller_id='your_seller_id')

**Comment by benliu723** [comment]
另外，关于wap支付这块，最新文档上的网关是：https://mapi.alipay.com/gateway.do，
call_back_url 好像改成了 return_url, 并没有找到 seller_account_name，

我不知道我理解的是否正确，在运行您写的代码的时候，发送请求获取token的请求时一直 报缺少了非空的业务参数

**Comment by lxneng** [comment]
@benliu723 新的 API 文档显示不区分 WAP 和 WEB ,  直接用 WEB 接口就好了
