### ISSUE TITLE
你好 请问一下django如何使用verify_notify方法？

### ISSUE THREAD

**Issue by 496080199** [lxneng/alipay#24]
verify_notify验证生成md5的sign和支付宝post过来的始终不一致，求解答

**Comment by lxneng** [comment]
@496080199 
试试decode一下返回过来的值
```py
data = {k: v.decode('utf8') for k, v in request.POST.items()}
alipay.verify_notify(**data)
```

**Comment by 496080199** [comment]
找到原因了，我用request.POST作为verify_notify的参数，request.POST是一个QueryDict对象，要转换为标准的Dict对象。request.POST.dict()
