### ISSUE TITLE
sign_type问题

### ISSUE THREAD

**Issue by wsqy** [lxneng/alipay#27]
我看的文档https://doc.open.alipay.com/docs/api.htm?spm=a219a.7395905.0.0.wItNMR&docType=4&apiId=862 sign_type 都是RSA 为什么你的封装签名中用的是MD5 文档中说只支持RSA和RSA2呀  难道我看的是假文档？

**Comment by rijn** [comment]
I suppose this lib do not support trade.precreate yet

**Comment by ChrisLeeGit** [comment]
@wsqy , you can refer this [repo](https://github.com/fzlee/alipay) :)

**Comment by sc-syf** [comment]
旧版的支付宝文档是md5的， 新版支付宝文档似乎只有RSA和RSA2了 →_→
